#!/usr/bin/env python3
"""SFT training for Memory-R1 agents (Memory Manager and Answer Agent).

Trains QLoRA adapters on Qwen-2.5-7B-Instruct using the training data
generated by prepare_r1_data.py.

Supports:
- Local smoke testing (CPU/MPS, small model, no quantization)
- Databricks GPU training (CUDA, QLoRA 4-bit, full training)

Usage:
    # Local smoke test (2 steps, tiny model, CPU)
    uv run python scripts/train_memory_r1.py --smoke-test

    # Full training on GPU
    uv run python scripts/train_memory_r1.py --agent mm
    uv run python scripts/train_memory_r1.py --agent aa

    # Both agents sequentially
    uv run python scripts/train_memory_r1.py --agent both
"""

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path

import torch
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer


# ============================================================
# Configuration
# ============================================================

DATA_DIR = Path(__file__).parent.parent / "data" / "r1_training"
OUTPUT_DIR = Path(__file__).parent.parent / "models"

# Model defaults
DEFAULT_MODEL = "Qwen/Qwen2.5-7B-Instruct"
SMOKE_TEST_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

# LoRA config (from plan: rank 64, alpha 64, dropout 0.05)
LORA_R = 64
LORA_ALPHA = 64
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]

# Training hyperparameters
MAX_SEQ_LENGTH = 4096
LEARNING_RATE = 2e-4
NUM_EPOCHS = 5
BATCH_SIZE = 2
GRADIENT_ACCUMULATION = 8  # Effective batch size = 16
WARMUP_RATIO = 0.05


@dataclass
class TrainingArgs:
    """Training arguments."""
    agent: str = "mm"  # "mm", "aa", or "both"
    model_name: str = DEFAULT_MODEL
    output_dir: str = str(OUTPUT_DIR)
    max_seq_length: int = MAX_SEQ_LENGTH
    num_epochs: int = NUM_EPOCHS
    batch_size: int = BATCH_SIZE
    gradient_accumulation: int = GRADIENT_ACCUMULATION
    learning_rate: float = LEARNING_RATE
    lora_r: int = LORA_R
    lora_alpha: int = LORA_ALPHA
    lora_dropout: float = LORA_DROPOUT
    bf16: bool = True
    smoke_test: bool = False
    max_steps: int = -1  # -1 means use num_epochs


# ============================================================
# Data Loading
# ============================================================


def load_jsonl(path: Path) -> list[dict]:
    """Load a JSONL file into a list of dicts."""
    examples = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))
    return examples


def load_sft_dataset(path: Path, tokenizer, max_seq_length: int) -> Dataset:
    """Load JSONL and convert to HuggingFace Dataset with tokenized chat format."""
    raw = load_jsonl(path)
    print(f"  Loaded {len(raw)} examples from {path.name}")

    # Apply chat template to convert messages to text
    texts = []
    skipped = 0
    for ex in raw:
        messages = ex["messages"]
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
        # Check token length and skip if too long
        token_len = len(tokenizer.encode(text))
        if token_len > max_seq_length:
            skipped += 1
            continue
        texts.append(text)

    if skipped:
        print(f"  Skipped {skipped} examples exceeding {max_seq_length} tokens")

    print(f"  Using {len(texts)} examples for training")
    return Dataset.from_dict({"text": texts})


# ============================================================
# Model Setup
# ============================================================


def detect_device(verbose: bool = True) -> tuple[str, torch.dtype]:
    """Detect the best available device and dtype."""
    if torch.cuda.is_available():
        if verbose:
            print("  Device: CUDA GPU")
        return "cuda", torch.bfloat16
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        if verbose:
            print("  Device: Apple MPS")
        return "mps", torch.float16  # MPS doesn't support bf16
    else:
        if verbose:
            print("  Device: CPU")
        return "cpu", torch.float32


def setup_model_and_tokenizer(args: TrainingArgs):
    """Load base model in full bf16 and apply LoRA. Paper uses full precision."""
    device, dtype = detect_device()

    print(f"\n=== Loading Model: {args.model_name} ===")
    print(f"  Precision: {dtype} (full, no quantization)")

    model_kwargs = {
        "dtype": dtype,
        "trust_remote_code": True,
        "device_map": "auto",
    }

    model = AutoModelForCausalLM.from_pretrained(args.model_name, **model_kwargs)

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        args.model_name, trust_remote_code=True
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Apply LoRA
    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=LORA_TARGET_MODULES,
        task_type=TaskType.CAUSAL_LM,
        bias="none",
    )
    model = get_peft_model(model, lora_config)

    # Print trainable parameters
    trainable, total = model.get_nb_trainable_parameters()
    pct = 100 * trainable / total
    print(f"  Trainable params: {trainable:,} / {total:,} ({pct:.2f}%)")

    return model, tokenizer, device


# ============================================================
# Training
# ============================================================


def train_agent(
    agent_name: str,
    model,
    tokenizer,
    args: TrainingArgs,
    device: str,
):
    """Train a single agent (Memory Manager or Answer Agent)."""
    print(f"\n{'='*60}")
    print(f"Training: {agent_name.upper()}")
    print(f"{'='*60}")

    # Determine data files
    if agent_name == "mm":
        train_path = DATA_DIR / "memory_manager_train.jsonl"
        val_path = DATA_DIR / "memory_manager_val.jsonl"
        adapter_name = "adapter_memory_manager"
    elif agent_name == "aa":
        train_path = DATA_DIR / "answer_agent_train.jsonl"
        val_path = DATA_DIR / "answer_agent_val.jsonl"
        adapter_name = "adapter_answer_agent"
    else:
        raise ValueError(f"Unknown agent: {agent_name}")

    # Load datasets
    print("\n--- Loading Data ---")
    train_ds = load_sft_dataset(train_path, tokenizer, args.max_seq_length)
    val_ds = load_sft_dataset(val_path, tokenizer, args.max_seq_length)

    # Output path
    adapter_path = Path(args.output_dir) / adapter_name
    adapter_path.mkdir(parents=True, exist_ok=True)

    # Determine effective training config
    max_steps = args.max_steps
    num_epochs = args.num_epochs
    if max_steps > 0:
        num_epochs = -1  # max_steps overrides

    # Training arguments
    training_args = SFTConfig(
        output_dir=str(adapter_path),
        num_train_epochs=num_epochs if max_steps <= 0 else 1,
        max_steps=max_steps if max_steps > 0 else -1,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation,
        learning_rate=args.learning_rate,
        lr_scheduler_type="cosine",
        warmup_ratio=WARMUP_RATIO if max_steps <= 0 else 0,
        max_length=args.max_seq_length,
        bf16=(args.bf16 and device == "cuda"),
        fp16=(device == "mps"),
        logging_steps=1 if args.smoke_test else 10,
        eval_strategy="no",
        save_strategy="epoch" if max_steps <= 0 else "no",
        save_total_limit=2,
        report_to="none",
        dataset_text_field="text",
        packing=False,
        gradient_checkpointing=True if device in ("cuda", "mps") else False,
        gradient_checkpointing_kwargs=(
            {"use_reentrant": False} if device in ("cuda", "mps") else None
        ),
        seed=42,
        dataloader_pin_memory=False,
    )

    # Create trainer
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
    )

    # Train
    print("\n--- Training ---")
    train_result = trainer.train()

    # Log results
    print(f"\n--- Results ---")
    print(f"  Train loss: {train_result.training_loss:.4f}")
    metrics = train_result.metrics
    for k, v in sorted(metrics.items()):
        if isinstance(v, float):
            print(f"  {k}: {v:.4f}")
        else:
            print(f"  {k}: {v}")

    # Skip eval — OOMs on pipeline-parallel sharded model (fp32 logits on one GPU)
    print("\n  Eval skipped (pipeline parallel OOM). Train loss logged during training.")

    # Save adapter
    if not args.smoke_test:
        print(f"\n--- Saving adapter to {adapter_path} ---")
        model.save_pretrained(str(adapter_path))
        tokenizer.save_pretrained(str(adapter_path))
        print("  Done.")

    return train_result


# ============================================================
# Main
# ============================================================


def parse_args() -> TrainingArgs:
    parser = argparse.ArgumentParser(description="Train Memory-R1 SFT agents")
    parser.add_argument(
        "--agent",
        choices=["mm", "aa", "both"],
        default="mm",
        help="Which agent to train: mm (Memory Manager), aa (Answer Agent), or both",
    )
    parser.add_argument(
        "--model",
        default=None,
        help=f"Model name/path (default: {DEFAULT_MODEL}, smoke: {SMOKE_TEST_MODEL})",
    )
    parser.add_argument(
        "--output-dir",
        default=str(OUTPUT_DIR),
        help=f"Output directory for adapters (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        help="Run minimal smoke test (tiny model, 3 steps, CPU-friendly)",
    )
    parser.add_argument("--max-steps", type=int, default=-1, help="Max training steps (-1 for epochs)")
    parser.add_argument("--epochs", type=int, default=NUM_EPOCHS, help="Number of epochs")
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--lr", type=float, default=LEARNING_RATE)
    parser.add_argument("--max-seq-length", type=int, default=MAX_SEQ_LENGTH)
    parser.add_argument("--lora-r", type=int, default=LORA_R)

    cli = parser.parse_args()

    args = TrainingArgs(
        agent=cli.agent,
        output_dir=cli.output_dir,
        num_epochs=cli.epochs,
        batch_size=cli.batch_size,
        learning_rate=cli.lr,
        max_seq_length=cli.max_seq_length,
        lora_r=cli.lora_r,
        max_steps=cli.max_steps,
    )

    # Smoke test overrides
    if cli.smoke_test:
        args.smoke_test = True
        args.model_name = cli.model or SMOKE_TEST_MODEL
        args.max_steps = 3
        args.batch_size = 1
        args.gradient_accumulation = 1
        args.max_seq_length = 2048
        args.lora_r = 8
        args.lora_alpha = 8
    else:
        args.model_name = cli.model or DEFAULT_MODEL

    # Auto-adjust batch size for large models on MPS to avoid OOM
    device, _ = detect_device(verbose=False)
    if (
        not args.smoke_test
        and device == "mps"
        and "7B" in args.model_name
        and cli.batch_size == BATCH_SIZE  # only override if user didn't set explicitly
    ):
        args.batch_size = 1
        args.gradient_accumulation = 16  # keep effective batch size = 16
        print(f"  MPS + 7B detected: auto-adjusted batch_size=1, grad_accum=16")

    return args


def main():
    args = parse_args()

    print("=" * 60)
    print("Memory-R1 SFT Training")
    print("=" * 60)
    print(f"  Agent(s): {args.agent}")
    print(f"  Model: {args.model_name}")
    print(f"  LoRA: r={args.lora_r}, alpha={args.lora_alpha}, dropout={args.lora_dropout}")
    print(f"  Max seq length: {args.max_seq_length}")
    print(f"  Precision: full bf16 (no quantization)")
    print(f"  Smoke test: {args.smoke_test}")
    if args.max_steps > 0:
        print(f"  Max steps: {args.max_steps}")
    else:
        print(f"  Epochs: {args.num_epochs}")
    print(f"  Batch: {args.batch_size} x {args.gradient_accumulation} = "
          f"{args.batch_size * args.gradient_accumulation}")
    print(f"  LR: {args.learning_rate}")
    print(f"  Output: {args.output_dir}")

    # Verify data exists
    for fname in ["memory_manager_train.jsonl", "answer_agent_train.jsonl"]:
        p = DATA_DIR / fname
        if not p.exists():
            print(f"\nError: {p} not found. Run prepare_r1_data.py first.")
            sys.exit(1)

    agents_to_train = ["mm", "aa"] if args.agent == "both" else [args.agent]

    for agent_name in agents_to_train:
        # Load model fresh for each agent (separate LoRA adapters)
        model, tokenizer, device = setup_model_and_tokenizer(args)
        train_agent(agent_name, model, tokenizer, args, device)

        # Free memory between agents
        if len(agents_to_train) > 1:
            del model, tokenizer
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    print("\n" + "=" * 60)
    print("TRAINING COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
